server:
  port: 7001

eureka:
  instance:
    # eureka 服务端实例名称
    # eureka服务端的实例名称
    # hostname: localhost
    hostname: eureka7001.com
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，我的职责是维护服务，不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      # 单机版
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 相互注册
      #defaultZone: http://eureka7002.com:7002/eureka/